# Generated by Django 5.0.6 on 2024-06-11 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_alter_exercise_options'),
        ('training_templates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingTemplateExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
                ('training_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training_templates.trainingtemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
