# Generated by Django 5.0.6 on 2024-06-11 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_templates', '0002_trainingtemplateexercise'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainingTemplateExercise',
        ),
    ]
