# Generated by Django 5.0.6 on 2024-06-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_alter_exercise_options'),
        ('training_templates', '0004_remove_trainingtemplate_exercises_exerciseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingtemplate',
            name='exercises',
            field=models.ManyToManyField(through='training_templates.ExerciseOrder', to='exercises.exercise'),
        ),
    ]
