# Generated by Django 5.0.6 on 2024-06-16 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_templates', '0005_trainingtemplate_exercises'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_type', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('reps', models.IntegerField()),
                ('exercise_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='training_templates.exerciseorder')),
            ],
        ),
    ]
