# Generated by Django 5.0.6 on 2024-06-19 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_templates', '0007_alter_set_set_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ['set_type']},
        ),
    ]
