# Generated by Django 5.0.6 on 2024-06-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_templates', '0008_alter_set_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': [models.Case(models.When(set_type='W', then=models.Value(0)), models.When(set_type__regex='^\\d+$', then=models.Value(1)), default=models.Value(2), output_field=models.IntegerField()), models.Case(models.When(set_type='W', then=models.Value(0)), default=models.F('set_type'), output_field=models.IntegerField())]},
        ),
    ]
