# Generated by Django 5.0.6 on 2024-06-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_templates', '0009_alter_set_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='set_type',
            field=models.CharField(choices=[('W', 'Warm Up'), ('N', 'Numbered')], default='N', max_length=2),
        ),
    ]
