# Generated by Django 5.0.6 on 2024-06-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_templates', '0010_alter_set_set_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='set_type',
            field=models.CharField(choices=[('W', 'Warm-up'), ('N', 'Numbered')], default='N', max_length=2),
        ),
    ]
