# Generated by Django 5.0.6 on 2024-06-06 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_alter_bodypart_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['main_body_part']},
        ),
    ]
