# Generated by Django 5.0.6 on 2024-06-11 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_alter_exercise_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['name']},
        ),
    ]
