# Generated by Django 5.0.6 on 2024-06-22 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_sessions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='user',
        ),
    ]
