# Generated by Django 5.0.6 on 2024-11-29 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_alter_exercise_options'),
        ('training_sessions', '0002_remove_trainingsession_user'),
        ('training_templates', '0011_alter_set_set_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionexercise',
            name='exercise_name',
            field=models.CharField(blank=True, help_text='Name of the exercise at the time of session creation.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='template_name',
            field=models.CharField(blank=True, help_text='Name of the template at the time of session creation.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sessionexercise',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercises.exercise'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training_templates.trainingtemplate'),
        ),
    ]
